### ISSUE TITLE
DataCue or a more specific API for DASH and emsg events

### ISSUE THREAD

**Issue by chrisn** [w3c/me-media-timed-events#2]
Our discussion so far in the IG has focused on `DataCue`, which as defined in the current [HTML 5.3 draft](https://www.w3.org/TR/2018/WD-html53-20180426/semantics-embedded-content.html#text-tracks-exposing-inband-metadata), and is not present in the WHATWG HTML Living Standard.

In addition to the `TextTrackCue` attributes (`startTime`, `endTime`, and `id`, among others), `DataCue` is defined as having a single `data` attribute.

In addition to the message payload, `emsg` and DASH events also contain `schema` and `value` strings. `schema` is a URI that identifies the message scheme, and `value` is described as "the value for the event" in the [MPEG DASH spec](http://standards.iso.org/ittf/PubliclyAvailableStandards/c065274_ISO_IEC_23009-1_2014.zip).

In practice - e.g., for RadioVIS (image slides alongside an audio stream) in [DVB](https://www.dvb.org/resources/public/standards/a168_dvb_mpeg-dash_nov_2017.pdf) (section 9.1.7) - a combination of `schema` and `value` is used to inform applications how to interpret the message payload data.

So I have two questions:

1. Is the existing `DataCue` as currently defined what we need, or should we aim for a more specific API that also exposes the `schema` and `value` values?
2. Is there a need for an API that allows applications to tell the UA which `schema`s it wants to receive, or should the UA simply expose all `emsg` events to applications?

**Comment by nigelmegitt** [comment]
There are other options to consider: 

- if you want to select some set of `emsg` events and there is identifying metadata in them, you could push that metadata up to the `TextTrack` level and have the `DataCue`s just contain the payload data for each one.

- if you want to create cues that have extra data in you could subclass `DataCue` to e.g. `emsgEventCue` and add attributes to that class.

So the broader question is: do we need, in the HTML spec, a common set of classes to use for MPEG DASH based events, or is there a more general construct that can be adapted for use in a more specific use case?

**Comment by silviapfeiffer** [comment]
So in WebVTT, we use the .text attribute to contain any kind of metadata, e.g. see https://webplatform.github.io/docs/concepts/VTT_Captioning/#Metadata-Tracks  .

JWplayer have implemented some nice versions of this:
https://support.jwplayer.com/articles/how-to-add-preview-thumbnails
https://support.jwplayer.com/articles/how-to-add-chapter-markers

I wonder if `emsg` events could simply be handled the same way.

**Comment by boblund** [comment]
If you use the VttCue text attribute, DataCue data attribute or some other generic mechanism, then there would need to be a specification to denote how the user agent would encode the attribute contents so that JavaScript could differentiate an emsg contained in the attribute from some other data type. This specification could be done in [1]. For what it's worth, there was some resistance when writing the HTML5 recommendation to a generic DataCue used in this way. The argument was that Cues should have an explicit type to avoid misuse, either by error or deliberate. An EmsgEventCue with uri, presentationTime, duration, id and emsgData attributes would be a more explicit way to expose emsgs that addresses this concern. The user agent work should be roughly the same in all cases since the UA still needs to detect the emsg and format it for whatever API.

[1] https://dev.w3.org/html5/html-sourcing-inband-tracks/

**Comment by boblund** [comment]
@silviapfeiffer that is what I meant by my remark "then there would need to be a specification to denote how the user agent would encode the attribute contents". In the case of your idea, if I understand it correctly, that encoding would actually be setting the the identifier correctly. [1] would be the place to define those identifiers.

AFAIK, Safari is the only browser that has implemented DataCue. VTTCue seems to be more widely implemented. 

[1] https://dev.w3.org/html5/html-sourcing-inband-tracks/

**Comment by silviapfeiffer** [comment]
Putting this JSON into .text on a VttCue is the easiest way of dealing with it:
`
{
      type: 'emsg',
      timestamp: 168271.6,
      detail: {
        messageData: [88, 89, 90 ....],
         eventDuration: 0,
         id: 1000300,
         presentationTimeDelta: 0,
         schemeIdUri: "urn:foo:bar:id3:2016",
         timescale: 48000
         value:"0"
      }
`

**Comment by nigelmegitt** [comment]
The data already has some format, so assuming it is not WebVTT, then a requirement to convert it into WebVTT and then use a VTTCue seems like unnecessary work. Overloading VTTCue also feels wrong, given that it is generic data and not text to be presented. From that perspective it looks better to start with a TextTrackCue, or a DataCue subclass, and go from there.

If I were designing the interface for DataCue I'd put the payload data into an attribute like `.data` or `.payload` rather than `.text` because it might not be text at all. Having a `.type` in the cue class might work. From an object-oriented design perspective it would be better to identify the type by the class, i.e. subclass DataCue into MyFormatDataCue - if a type query is needed then that would require inspection of the object's class rather than an attribute of the object. Both ways can be made to work.

**Comment by boblund** [comment]
The JSON proposed by @silviapfeiffer captures the contents of emsg. Does this task force agree that it meets the requirement to expose emsgs to JavaScript?

Then there is the question of API requirements. Seems to me that any of: 1) TextTrackCue.text, 2) VTTCue.text,  3) DataCue.data and 4) a dedicated EmsgEventCue could be used to convey the emsg data. In HTML5, the creation of DataCue resulted from the decision to drop the .text attribute from TextTrackCue. Semantically, they seem the same to me; both are exposing opaque data intended for JavaScript that will not be processed by the browser. There was a discussion [1] about adding the .text attribute back to TextTrackCue, which would seem to obviate the need for DataCue, but I don't see it in either WC3 HTML5.2 or WHATWG.

VTTCue.text is attractive since it exists but I agree with @nigelmegitt  that exposing emsgs as WebVTT feels a little awkward.

EmsgEventCue (as a subclass of TextTrackCue) seems like the most straightforward API for JavaScript use. Plus, the sub-typing approach seems to be what the HTML authors have in mind.

A related question is what other Cue formats are under consideration, e.g. TTML? Should the task force consider the broader set of requirements and approaches?

[1] https://www.w3.org/html/wg/wiki/User:Spfeiffe/TextTrackChange

**Comment by mavgit** [comment]
I'm so glad we're making progress in this area, but please move any further discussion to a new thread in the [WICG Discourse forum](https://discourse.wicg.io) for several reasons.

The biggest issue is that W3C Interest Groups have no IP coverage. Therefore, the IG is mandated to limit our discussion to requirements and use cases only. This thread is getting into explicit and detailed API design. W3C Community Groups, like WICG, have IP coverage and are created for API design. We don't want to undermine the W3C RF license.

Another reason is that there is much more participation by browser implementation teams in WICG and the most recent posts relate to browser implementation issues.

Finally, as I mentioned in the first Task Force call, we should get this discussion into WICG as soon as possible in order to get implementation as soon as possible.

Please close this thread and start a new thread in WICG. Other TF threads concerning requirements and use cases are welcome in this IG Task Force repo, but any other threads that also get into API design should happen in WICG.

**Comment by chrisn** [comment]
I agree with Mark, the next step for this is to raise the topic in WICG.

This discussion has gone slightly further than I anticipated, the intent behind my original question was to simply determine whether our ask is for `DataCue` or something more specific to `emsg`.

Thank you everyone for your input here. I'll summarise requirements:

* The API must expose `emsg` events to Web applications, and include all fields, including `schema`, `value`, and `message_data`
* The API must allow Web applications to create such events (to allow handling of events in the MPD)
* The API must trigger events at the right point in the media timeline during media playback

Whether the appropriate solution is to expose via an `EMSGCue` or `VTTCue` or other API is best discussed with implementer input, so let's do that in WICG.

The one requirements-level question that I would like to ask before we move the discussion to WICG is: Exactly why is a native API needed, and can the same effect not be achieved through application level script?

**Comment by silviapfeiffer** [comment]
None of this is new IP - all of it has been discussed many times over in the TextTrack CG, WHATWG and the HTML WG. A change to specs and implementations isn't going to take place here anyway.

What we can get to here is a feeling for what preferences people have in this community before taking it to the right community to address it.

@boblund has nicely listed the alternatives. Here are the problems with each:

1) TextTrackCue.text
* does not exist in the HTML5 spec any longer
* will most likely not come back in the HTML spec
* needs an extra way to specify the data type, e.g. .dataType attribute

2) VTTCue.text
* exists in HTML5 API, is supported by browsers
* WebVTT can bring metadata into HTML pages via `<track>` element now
* needs an extra way to specify the data type, e.g. .dataType attribute

3) DataCue.data
* exists in spec, but is not implemented in browsers
* needs an extra way to specify the data type, e.g. .dataType attribute
* seems sensible in the long run to allow this as a generic framework for associating structured data with a time interval

4) a dedicated EmsgEventCue
* needs a completely new spec and implementation
* seems overkill for anything that doesn't have a huge use in practice

So, your decision may depend on how long you are prepared to wait for it to become usable in a Web browser.

I suggested (2) as an interim measure, but it's not the best and most generic solution. It will, however, work now and it has the advantage that you can also carry emsg events in a WebVTT file and associate it with a video element via the `<track>` element in HTML right now. 

Whether your preference is on (3) or (4) going forward should depend on the size of your "market" - how many users and use cases do you see? I personally would prefer to start with (3).

So, give your opinions here and then you'll need to take it straight to the HTML WG or the WHATWG for specification and implementer buy-in. If you want to pass it by any further forums for further buy-in, go ahead also.

**Comment by chrisn** [comment]
Let's follow up in the [WICG DataCue incubation][1]. Thank you @boblund and @silviapfeiffer for clearly summarising the various options.

[1]: https://github.com/WICG/datacue
